# Generated by Django 4.2.21 on 2025-05-16 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valuation_date",
                    models.DateField(db_index=True, verbose_name="Date"),
                ),
                (
                    "rate_value",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=6,
                        max_digits=18,
                        verbose_name="Rate",
                    ),
                ),
                (
                    "exchanged_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanges_in",
                        to="currencies.currency",
                    ),
                ),
                (
                    "source_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanges_out",
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "ordering": ("-valuation_date",),
                "unique_together": {
                    ("source_currency", "exchanged_currency", "valuation_date")
                },
            },
        ),
    ]
