# Generated by Django 4.2.21 on 2025-05-18 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0002_alter_currency_name_alter_currency_symbol"),
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyexchangerate",
            name="exchanged_currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="currencies.currency"
            ),
        ),
        migrations.AlterField(
            model_name="currencyexchangerate",
            name="rate_value",
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name="currencyexchangerate",
            name="source_currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchanges",
                to="currencies.currency",
            ),
        ),
        migrations.AlterField(
            model_name="currencyexchangerate",
            name="valuation_date",
            field=models.DateField(db_index=True),
        ),
    ]
