# Generated by Django 4.2.21 on 2025-05-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=3, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("symbol", models.CharField(max_length=8, verbose_name="Symbol")),
            ],
        ),
    ]
