# Generated by Django 4.2.21 on 2025-05-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(db_index=True, max_length=20, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="currency",
            name="symbol",
            field=models.CharField(max_length=10, verbose_name="Symbol"),
        ),
    ]
